version: "1"

services:

  app:
    image: my-app:latest

    container_name: my-app-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
    ports:
      - 9093:9092
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: mydb-kiii
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: