version: '3.8'

services:
  my-app:
    image: my-app-image:latest
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge