version: "1"

services:

  app:
    image: my-app-image:latest

    container_name: teamplayerapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
    ports:
      - 8081:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: mydb-kiii
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: