name: Build and Push Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image

        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

      - name: Verify Docker image
        run: docker run -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest